#! /usr/bin/env python

from distutils.version import LooseVersion
import json

import requests

from common import get_package_url
from common import get_payload
from common import get_version


def check():
    payload = get_payload()
    url = get_package_url(payload)
    version = get_version(payload)

    response = requests.get(url, headers={'accept': 'application/json'}).json()
    versions = sorted([LooseVersion(v) for v in response['result'].keys()])
    result = [{'version': v.vstring} for v in versions]

    if versions and (version is None or version == versions[-1].vstring):
        print(json.dumps([result[-1]]))
    else:
        print(json.dumps(result))


if __name__ == '__main__':
    check()
